<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2fef1dea-c569-438b-9633-b793650e6b04</elementGuidId>
    <imagePath></imagePath>
    <name>input_delivery_id_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/fieldset[1]/div[1]/label[2]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'delivery_id')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>delivery_id</value>
        <webElementGuid>8347c09b-0b22-4e49-891c-d0dcb37067b3</webElementGuid>
    </webElementProperties>
</WebElementEntity>