<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e3e9e370-a4ef-4394-abe1-41947de9035f</elementGuidId>
    <imagePath></imagePath>
    <name>input_payment_method_id</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'payment_method_id')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>payment_method_id</value>
        <webElementGuid>6746a2fc-f039-473e-8b96-86c980eab087</webElementGuid>
    </webElementProperties>
</WebElementEntity>